# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend_Basic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Path_label = QtWidgets.QLabel(self.centralwidget)
        self.Path_label.setGeometry(QtCore.QRect(11, 10, 63, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Path_label.setFont(font)
        self.Path_label.setObjectName("Path_label")
        self.Browse_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Browse_pushButton.setGeometry(QtCore.QRect(533, 13, 75, 23))
        self.Browse_pushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.Browse_pushButton.setObjectName("Browse_pushButton")
        self.Dialogue_label = QtWidgets.QLabel(self.centralwidget)
        self.Dialogue_label.setGeometry(QtCore.QRect(11, 46, 63, 495))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dialogue_label.setFont(font)
        self.Dialogue_label.setObjectName("Dialogue_label")
        self.Run_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Run_pushButton.setGeometry(QtCore.QRect(533, 510, 75, 23))
        self.Run_pushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.Run_pushButton.setObjectName("Run_pushButton")
        self.Dialogue_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Dialogue_textBrowser.setGeometry(QtCore.QRect(80, 46, 447, 495))
        self.Dialogue_textBrowser.setMaximumSize(QtCore.QSize(900, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dialogue_textBrowser.setFont(font)
        self.Dialogue_textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Dialogue_textBrowser.setObjectName("Dialogue_textBrowser")
        self.Path_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Path_textBrowser.setGeometry(QtCore.QRect(80, 10, 447, 30))
        self.Path_textBrowser.setMaximumSize(QtCore.QSize(900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Path_textBrowser.setFont(font)
        self.Path_textBrowser.setObjectName("Path_textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Path_label.setText(_translate("MainWindow", "Excel Path:"))
        self.Browse_pushButton.setText(_translate("MainWindow", "Browse"))
        self.Dialogue_label.setText(_translate("MainWindow", "Dialogue:"))
        self.Run_pushButton.setText(_translate("MainWindow", "Run"))
